/* eslint-disable */
/**
 * Generated `api` utility.
 *
 * THIS CODE IS AUTOMATICALLY GENERATED.
 *
 * Generated by convex@1.11.2.
 * To regenerate, run `npx convex dev`.
 * @module
 */

import type {
  ApiFromModules,
  FilterApi,
  FunctionReference,
} from "convex/server";
import type * as event from "../event.js";
import type * as eventfromid from "../eventfromid.js";
import type * as events from "../events.js";
import type * as getscholarship from "../getscholarship.js";
import type * as scholarship from "../scholarship.js";
import type * as useapimutation from "../useapimutation.js";

/**
 * A utility for referencing Convex functions in your app's API.
 *
 * Usage:
 * ```js
 * const myFunctionReference = api.myModule.myFunction;
 * ```
 */
declare const fullApi: ApiFromModules<{
  event: typeof event;
  eventfromid: typeof eventfromid;
  events: typeof events;
  getscholarship: typeof getscholarship;
  scholarship: typeof scholarship;
  useapimutation: typeof useapimutation;
}>;
export declare const api: FilterApi<
  typeof fullApi,
  FunctionReference<any, "public">
>;
export declare const internal: FilterApi<
  typeof fullApi,
  FunctionReference<any, "internal">
>;
